#!/bin/bash

# Obtiene la información de la canción actual
status=$(playerctl status 2>/dev/null)

if [ "$status" = "Playing" ] || [ "$status" = "Paused" ]; then
    artist=$(playerctl metadata artist)
    title=$(playerctl metadata title)
    echo "$title-$artist "
else
    echo ""
fi

